### ISSUE TITLE
Conflicting Licenses

### ISSUE THREAD

**Issue by jtcmedia** [CountDeMonet/FlightConnect#1]
In the root of your project, you have a LICENSE file that has opened sourced it under Apache License 2.0 but in the `SimConnectSysTray` folder, a commercial license is still there (`FlightConnect_License.rtf`). Can that be removed to make it clear which license this software falls under?

**Comment by CountDeMonet** [comment]
That was the binary distribution license from before I opensourced the project. I forgot it was in there. I have removed it

**Comment by jtcmedia** [comment]
Thanks!
